#!/usr/bin/env python3
# mcp-agent-mail guard plugin (pre-push)
# project: frankenpandas
# Auto-generated by mcp-agent-mail install_guard

import datetime
import fnmatch
import json
import os
import re
import subprocess
import sys

PROJECT = "frankenpandas"
HOOK_NAME = "pre-push"
AGENT_NAME = os.environ.get("AGENT_NAME", "").strip()
GUARD_MODE = os.environ.get("AGENT_MAIL_GUARD_MODE", "block")

def get_staged_files():
    """Get list of staged files from git (for pre-commit)."""
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-status", "-M", "-z", "--diff-filter=ACMRDTU"],
            capture_output=True, check=True,
        )
        data = result.stdout or b""
        if not data:
            return []
        parts = data.split(b"\0")
        files = []
        i = 0
        while i < len(parts):
            if not parts[i]:
                break
            status = parts[i].decode("utf-8", "ignore")
            i += 1
            if status.startswith(("R", "C")):
                # Rename/Copy: next two entries are old and new path.
                if i + 1 >= len(parts):
                    break
                oldp = parts[i].decode("utf-8", "ignore")
                newp = parts[i + 1].decode("utf-8", "ignore")
                i += 2
                if oldp:
                    files.append(oldp)
                if newp:
                    files.append(newp)
            else:
                # Normal entry: next is the path.
                if i >= len(parts):
                    break
                p = parts[i].decode("utf-8", "ignore")
                i += 1
                if p:
                    files.append(p)
        # De-duplicate while preserving order.
        seen = set()
        out = []
        for f in files:
            if f not in seen:
                seen.add(f)
                out.append(f)
        return out
    except subprocess.CalledProcessError as exc:
        print(
            "mcp-agent-mail: guard failed to inspect staged files: " + str(exc),
            file=sys.stderr,
        )
        sys.exit(2)
    except Exception as exc:
        print(
            "mcp-agent-mail: guard failed to inspect staged files: " + str(exc),
            file=sys.stderr,
        )
        sys.exit(2)

def get_push_files():
    """Get list of files modified in the push (for pre-push)."""
    files = set()
    try:
        # Read stdin for ref updates (local_ref local_sha remote_ref remote_sha)
        # sys.stdin.read() works because chain-runner pipes input as text/bytes depending on OS,
        # but in Python 3 sys.stdin is a text wrapper. The chain-runner sends raw bytes,
        # but standard python environment usually handles this.
        # Safe fallback is sys.stdin.read().
        stdin_data = sys.stdin.read()
        if not stdin_data:
            return []

        for line in stdin_data.splitlines():
            parts = line.split()
            if len(parts) < 4:
                continue
            local_sha = parts[1]
            remote_sha = parts[3]

            # Skip deletes
            if set(local_sha) == {'0'}:
                continue

            if set(remote_sha) == {'0'}:
                rev_list_args = ["git", "rev-list", "--topo-order", local_sha, "--not", "--remotes"]
            else:
                rev_list_args = ["git", "rev-list", "--topo-order", f"{remote_sha}..{local_sha}"]

            # Get commits in range
            res = subprocess.run(
                rev_list_args,
                capture_output=True, text=True
            )
            if res.returncode != 0:
                detail = (res.stderr or "").strip()
                if not detail:
                    detail = f"git rev-list exited with status {res.returncode}"
                print(
                    "mcp-agent-mail: guard failed to enumerate pushed commits: " + detail,
                    file=sys.stderr,
                )
                sys.exit(2)

            commits = [c.strip() for c in res.stdout.splitlines() if c.strip()]

            for sha in commits:
                diff_res = subprocess.run(
                    ["git", "diff-tree", "-r", "--no-commit-id", "--name-status",
                     "-M", "--no-ext-diff", "--diff-filter=ACMRDTU", "-z", "-m", sha],
                    capture_output=True
                )
                if diff_res.returncode != 0:
                    detail = diff_res.stderr.decode("utf-8", "ignore").strip()
                    if not detail:
                        detail = f"git diff-tree exited with status {diff_res.returncode}"
                    print(
                        "mcp-agent-mail: guard failed to inspect pushed commit paths: " + detail,
                        file=sys.stderr,
                    )
                    sys.exit(2)
                data = diff_res.stdout
                parts = data.split(b'\0')
                i = 0
                while i < len(parts):
                    status = parts[i].decode('utf-8', 'ignore').strip()
                    if not status:
                        i += 1
                        continue
                    i += 1
                    if status.startswith(('R', 'C')):
                        if i + 1 < len(parts):
                            oldp = parts[i].decode('utf-8', 'ignore')
                            newp = parts[i+1].decode('utf-8', 'ignore')
                            if oldp: files.add(oldp)
                            if newp: files.add(newp)
                            i += 2
                    else:
                        if i < len(parts):
                            p = parts[i].decode('utf-8', 'ignore')
                            if p: files.add(p)
                            i += 1
    except Exception as exc:
        print(
            "mcp-agent-mail: guard failed to inspect push files: " + str(exc),
            file=sys.stderr,
        )
        sys.exit(2)
    return sorted(list(files))

def is_real_directory(path):
    try:
        return os.path.isdir(path) and not os.path.islink(path)
    except OSError:
        return False

def is_real_file(path):
    try:
        return os.path.isfile(path) and not os.path.islink(path)
    except OSError:
        return False

def slugify(value):
    out = []
    prev_dash = False
    for ch in value.strip().lower():
        # Match Rust's is_ascii_alphanumeric() behavior
        if (ord(ch) >= 97 and ord(ch) <= 122) or (ord(ch) >= 48 and ord(ch) <= 57):
            out.append(ch)
            prev_dash = False
        elif not prev_dash:
            out.append("-")
            prev_dash = True
    slug = "".join(out).strip("-")
    return slug or "project"

def default_storage_root():
    for key in ("STORAGE_ROOT", "AGENT_MAIL_STORAGE_ROOT"):
        value = os.environ.get(key, "").strip()
        if value:
            return os.path.expanduser(value)
    
    # Match Rust core's default_storage_root_path logic
    legacy = os.path.expanduser("~/.mcp_agent_mail_git_mailbox_repo")
    if os.path.exists(legacy):
        return legacy
        
    # XDG Data path fallback
    xdg_data = os.environ.get("XDG_DATA_HOME")
    if xdg_data:
        root = os.path.join(xdg_data, "mcp-agent-mail", "git_mailbox_repo")
    else:
        root = os.path.expanduser("~/.local/share/mcp-agent-mail/git_mailbox_repo")
    return root

def get_repo_root():
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        value = (result.stdout or "").strip()
        return value or None
    except Exception:
        return None

def canonical_text(value):
    if not value:
        return ""
    try:
        return os.path.realpath(value)
    except OSError:
        return os.path.abspath(value)

def looks_like_project_slug(value):
    value = (value or "").strip()
    return bool(value) and not os.path.isabs(value) and "/" not in value and "\\" not in value

def project_metadata_matches(
    metadata,
    project_value,
    project_slug,
    repo_root,
    repo_slug,
    canonical_project,
    canonical_repo,
):
    if not isinstance(metadata, dict):
        return False

    slug = str(metadata.get("slug", "")).strip()
    project_value_is_slug = looks_like_project_slug(project_value)
    repo_root_is_slug = looks_like_project_slug(repo_root)
    if slug:
        if project_value_is_slug and slug in {project_value, project_slug}:
            return True
        if repo_root_is_slug and slug in {repo_root, repo_slug}:
            return True

    human_key = str(metadata.get("human_key", "")).strip()
    if human_key and human_key in {project_value, repo_root}:
        return True

    canonical_human_key = canonical_text(human_key)
    return bool(canonical_human_key and canonical_human_key in {canonical_project, canonical_repo})

def resolve_archive_root():
    repo_root = get_repo_root()
    if repo_root and is_real_directory(os.path.join(repo_root, "file_reservations")):
        return repo_root

    storage_root = default_storage_root()
    projects_dir = os.path.join(storage_root, "projects")
    if not is_real_directory(projects_dir):
        return None

    project_value = PROJECT.strip()
    project_slug = slugify(project_value) if project_value else ""
    repo_slug = slugify(repo_root) if repo_root else ""
    project_value_is_slug = looks_like_project_slug(project_value)
    repo_root_is_slug = looks_like_project_slug(repo_root)
    explicit_names = []
    for name in (
        project_value if project_value_is_slug else "",
        project_slug if project_value_is_slug else "",
        repo_root if repo_root_is_slug else "",
        repo_slug if repo_root_is_slug else "",
    ):
        if (
            name
            and not os.path.isabs(name)
            and "/" not in name
            and "\\" not in name
            and name not in explicit_names
        ):
            explicit_names.append(name)

    for name in explicit_names:
        candidate = os.path.join(projects_dir, name)
        if is_real_directory(os.path.join(candidate, "file_reservations")):
            return candidate

    canonical_project = canonical_text(project_value)
    canonical_repo = canonical_text(repo_root)
    try:
        entries = sorted(os.scandir(projects_dir), key=lambda entry: entry.name)
    except OSError:
        return None

    for entry in entries:
        try:
            if not entry.is_dir(follow_symlinks=False):
                continue
        except OSError:
            continue

        candidate = entry.path
        if not is_real_directory(os.path.join(candidate, "file_reservations")):
            continue
        if entry.name in explicit_names:
            return candidate

        metadata_path = os.path.join(candidate, "project.json")
        if not is_real_file(metadata_path):
            continue
        try:
            with open(metadata_path, "r", encoding="utf-8") as handle:
                metadata = json.load(handle)
        except Exception:
            continue
        if project_metadata_matches(
            metadata,
            project_value,
            project_slug,
            repo_root or "",
            repo_slug,
            canonical_project,
            canonical_repo,
        ):
            return candidate

    return None

def released_ts_marks_released(value):
    if value is None:
        return False
    if isinstance(value, (int, float)):
        return value > 0
    if isinstance(value, str):
        trimmed = value.strip()
        lowered = trimmed.lower()
        if lowered in ("", "0", "null", "none"):
            return False
        if all(ch.isdigit() or ch in ".+-" for ch in trimmed):
            try:
                return float(trimmed) > 0
            except ValueError:
                return False
        return True
    return False

def is_expired(value, now):
    if value is None:
        return True
    if isinstance(value, (int, float)):
        return value <= now.timestamp() * 1_000_000
    if isinstance(value, str):
        trimmed = value.strip()
        if not trimmed:
            return True
        if all(ch.isdigit() or ch in ".+-" for ch in trimmed):
            try:
                return float(trimmed) <= now.timestamp() * 1_000_000
            except ValueError:
                return False
        try:
            dt = datetime.datetime.fromisoformat(trimmed.replace("Z", "+00:00"))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=datetime.timezone.utc)
            return dt <= now
        except Exception:
            return False
    return False

def get_active_reservations():
    """Read active file reservations directly from the archive."""
    archive_root = resolve_archive_root()
    if not archive_root:
        print(
            f"mcp-agent-mail: guard could not locate archive for project {PROJECT!r}",
            file=sys.stderr,
        )
        sys.exit(2)

    reservations_dir = os.path.join(archive_root, "file_reservations")
    if not is_real_directory(reservations_dir):
        return []

    now = datetime.datetime.now(datetime.timezone.utc)
    active = []
    try:
        entries = sorted(os.scandir(reservations_dir), key=lambda entry: entry.name)
    except OSError as exc:
        print("mcp-agent-mail: guard failed to read reservations: " + str(exc), file=sys.stderr)
        sys.exit(2)

    for entry in entries:
        try:
            if not entry.is_file(follow_symlinks=False):
                continue
        except OSError:
            continue
        if not entry.name.endswith(".json"):
            continue
        if entry.is_symlink():
            continue
        try:
            with open(entry.path, "r", encoding="utf-8") as handle:
                record = json.load(handle)
        except Exception:
            continue

        if released_ts_marks_released(record.get("released_ts")):
            continue
        if is_expired(record.get("expires_ts"), now):
            continue

        pattern = str(record.get("path_pattern") or record.get("path") or "").strip()
        holder = str(record.get("agent_name") or record.get("agent") or "").strip()
        if not pattern or not holder or record.get("exclusive") is not True:
            continue

        active.append(
            {
                "path_pattern": pattern,
                "agent_name": holder,
                "expires_ts": record.get("expires_ts"),
            }
        )

    return active

def core_ignorecase_enabled():
    """Detect git core.ignorecase for path comparison parity with Rust guard."""
    try:
        res = subprocess.run(
            ["git", "config", "--bool", "core.ignorecase"],
            capture_output=True,
            text=True,
        )
        if res.returncode == 0:
            value = (res.stdout or "").strip().lower()
            return value in ("1", "true", "yes", "on")
    except Exception:
        pass
    # Windows repositories are usually case-insensitive by default.
    return os.name == "nt"

CASE_INSENSITIVE_REPO = core_ignorecase_enabled()

def normalize_match_input(value):
    # Normalize slashes and trim leading/trailing slashes
    val = value.replace('\\', '/').strip('/')
    # Collapse redundant segments (like Rust core normalization)
    parts = []
    for component in val.split('/'):
        if component == '' or component == '.':
            continue
        if component == '..':
            if parts:
                parts.pop()
        else:
            parts.append(component)
    val = '/'.join(parts)
    return val.lower() if CASE_INSENSITIVE_REPO else val

def glob_to_regex(pattern):
    """Convert shell-style glob to regex supporting **, [], and {} syntax."""
    # Hide ** so fnmatch does not convert it to .*
    pattern = pattern.replace("**", "\0")
    regex = fnmatch.translate(pattern)
    
    # Strip Python regex wrappers added by fnmatch
    if regex.startswith("(?s:"):
        regex = regex[4:]
    if regex.endswith(")\\Z"):
        regex = regex[:-3]
    elif regex.endswith("\\Z"):
        regex = regex[:-2]
    elif regex.endswith("$"):
        regex = regex[:-1]
        
    # Replace fnmatch's normal * (.*) with [^/]* to respect directory boundaries
    regex = regex.replace(".*", "[^/]*")
    # Restore ** logic, handling optional slashes
    regex = regex.replace("/\0/", "(?:/|/.+/)")
    if regex.startswith("\0/"):
        regex = "(?:.+/|)" + regex[2:]
    regex = regex.replace("\0", ".*")
    # Handle {a,b} bash-style brace expansion
    regex = re.sub(r"\\?\{(.+?)\\?\}", lambda m: "(" + m.group(1).replace("\\", "").replace(",", "|") + ")", regex)
    return regex

def glob_match(path, pattern):
    """Simple shell-style glob matching (similar to Rust implementation)."""
    # NOTE: path must be a concrete path, pattern is the glob.
    normalized_f = normalize_match_input(path)
    normalized_pattern = normalize_match_input(pattern)
    if not normalized_f or not normalized_pattern:
        return False
    try:
        return re.fullmatch(glob_to_regex(normalized_pattern), normalized_f) is not None
    except re.error:
        return False

def check_conflicts(paths, reservations):
    """Check if any paths conflict with active reservations."""
    self_agent = AGENT_NAME.lower()
    conflicts = []
    for f in paths:
        normalized_f = normalize_match_input(f)
        if not normalized_f:
            continue

        for res in reservations:
            pattern = res["path_pattern"]
            holder = res.get("agent_name", "unknown")
            if holder.lower() == self_agent:
                continue  # Skip our own reservations

            normalized_pattern = normalize_match_input(pattern)
            if not normalized_pattern:
                continue

            # 1. Glob matching: check if concrete path matches reserved glob
            if glob_match(normalized_f, normalized_pattern):
                conflicts.append((f, pattern, holder))
                break
            
            # Directory prefix matching
            has_glob = any(c in pattern for c in "*?[{")
            
            # 2. Reverse check: pattern is inside touched path (e.g. dir replaced by file)
            # This handles cases where a concrete parent directory is touched.
            if normalized_pattern.startswith(normalized_f + "/"):
                conflicts.append((f, pattern, holder))
                break

            # 3. Normal prefix check: file is inside reserved dir
            # This handles literal directory reservations.
            if not has_glob and normalized_f.startswith(normalized_pattern + "/"):
                conflicts.append((f, pattern, holder))
                break
    return conflicts

def is_truthy(val):
    if not val:
        return False
    return str(val).strip().lower() in ("1", "true", "t", "yes", "y")

def main():
    if not AGENT_NAME:
        print("mcp-agent-mail: AGENT_NAME environment variable is required.", file=sys.stderr)
        sys.exit(2)

    if is_truthy(os.environ.get("AGENT_MAIL_BYPASS")):
        sys.exit(0)

    enforcement_enabled = os.environ.get("FILE_RESERVATIONS_ENFORCEMENT_ENABLED")
    if enforcement_enabled is not None and not is_truthy(enforcement_enabled):
        sys.exit(0)

    if HOOK_NAME == "pre-push":
        files_to_check = get_push_files()
    else:
        files_to_check = get_staged_files()

    if not files_to_check:
        sys.exit(0)

    reservations = get_active_reservations()
    if not reservations:
        sys.exit(0)

    conflicts = check_conflicts(files_to_check, reservations)
    if not conflicts:
        sys.exit(0)

    msg = "mcp-agent-mail: file reservation conflict detected!\n"
    for path, pattern, holder in conflicts:
        msg += f"  {path} conflicts with reservation '{pattern}' held by {holder}\n"

    if GUARD_MODE == "warn":
        print(f"WARNING: {msg}", file=sys.stderr)
        sys.exit(0)
    else:
        print(f"ERROR: {msg}", file=sys.stderr)
        print("Set AGENT_MAIL_GUARD_MODE=warn to allow commit anyway.", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
