#!/usr/bin/env python3
"""Generate COVERAGE_MATRIX.md comparing pandas API surface to fixture coverage.

Per br-frankenpandas-zk1j: consumes
`artifacts/pandas_api_listing.json` (from
`scripts/gen_pandas_api_listing.py`) and grep of operation strings
in `crates/fp-conformance/fixtures/packets/*.json`, then writes a
Markdown matrix classifying each pandas API member as:

    Full    → a fixture references it by operation string
    Zero    → no fixture references it

(Partial is reserved for future per-signature coverage.)

Usage:
    python3 scripts/gen_pandas_api_listing.py   # populate listing
    python3 scripts/gen_coverage_matrix.py      # emit COVERAGE_MATRIX.md
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path


FIXTURE_GLOB = "crates/fp-conformance/fixtures/packets/*.json"
OPERATION_RE = re.compile(r'"operation"\s*:\s*"([^"]+)"')


def load_fixture_ops(repo_root: Path) -> set[str]:
    ops: set[str] = set()
    for fixture in repo_root.glob(FIXTURE_GLOB):
        try:
            text = fixture.read_text()
        except OSError:
            continue
        ops.update(OPERATION_RE.findall(text))
    return ops


# Map a pandas {class, member} pair to the operation strings our fixtures
# and oracle dispatch might carry. Multiple alias forms are common
# (e.g. "series_add", "data_frame_add"). Heuristic normalization handles
# the two dominant spellings.
def candidate_op_strings(class_alias: str, member_name: str) -> set[str]:
    cls_snake = _camel_to_snake(class_alias)
    forms = {
        f"{cls_snake}_{member_name}",
        f"{cls_snake.replace('_', '')}_{member_name}",
    }
    # Ad-hoc aliases seen in pandas_oracle.py dispatch (groupby_sum etc.).
    if cls_snake.endswith("group_by"):
        alt = cls_snake.replace("_group_by", "groupby").replace("group_by", "groupby")
        forms.add(f"{alt}_{member_name}")
    if cls_snake == "series":
        forms.add(f"series_{member_name}")
    if cls_snake == "data_frame":
        forms.add(f"dataframe_{member_name}")
    return forms


def _camel_to_snake(name: str) -> str:
    # CamelCase → camel_case
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def classify(
    listing: dict, fixture_ops: set[str]
) -> tuple[dict[str, dict[str, list[str]]], dict[str, dict[str, int]]]:
    """Returns (breakdown, counts):
    breakdown[class] = {"full": [...], "zero": [...]}
    counts[class] = {"full": N, "zero": N, "total": N}
    """
    breakdown: dict[str, dict[str, list[str]]] = defaultdict(
        lambda: {"full": [], "zero": []}
    )
    counts: dict[str, dict[str, int]] = {}
    for class_alias, entry in listing.get("classes", {}).items():
        if not isinstance(entry, dict) or "members" not in entry:
            continue
        for member in entry["members"]:
            cands = candidate_op_strings(class_alias, member["name"])
            hit = bool(cands & fixture_ops)
            bucket = "full" if hit else "zero"
            breakdown[class_alias][bucket].append(member["name"])
        full_n = len(breakdown[class_alias]["full"])
        zero_n = len(breakdown[class_alias]["zero"])
        counts[class_alias] = {
            "full": full_n,
            "zero": zero_n,
            "total": full_n + zero_n,
        }
    return breakdown, counts


def render(breakdown, counts, pandas_version: str) -> str:
    lines: list[str] = []
    lines.append("# Coverage Matrix")
    lines.append("")
    lines.append(
        f"Auto-generated by `scripts/gen_coverage_matrix.py` against "
        f"pandas **{pandas_version}** (from `artifacts/pandas_api_listing.json`). "
        "Re-run both scripts after upgrading pandas."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Class | Full | Zero | Total | Coverage |")
    lines.append("|---|---:|---:|---:|---:|")
    total_full = total_zero = 0
    for cls, c in sorted(counts.items()):
        pct = (c["full"] / c["total"] * 100) if c["total"] else 0.0
        lines.append(
            f"| {cls} | {c['full']} | {c['zero']} | {c['total']} | {pct:.1f}% |"
        )
        total_full += c["full"]
        total_zero += c["zero"]
    total = total_full + total_zero
    total_pct = (total_full / total * 100) if total else 0.0
    lines.append(
        f"| **ALL** | **{total_full}** | **{total_zero}** | **{total}** | "
        f"**{total_pct:.1f}%** |"
    )
    lines.append("")
    lines.append("## Per-class breakdown")
    for cls, b in sorted(breakdown.items()):
        lines.append("")
        lines.append(f"### {cls}")
        full = sorted(b["full"])
        zero = sorted(b["zero"])
        lines.append("")
        lines.append(f"**Full ({len(full)}):** {', '.join(full) if full else '_none_'}")
        lines.append("")
        lines.append(f"**Zero ({len(zero)}):** {', '.join(zero) if zero else '_none_'}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate COVERAGE_MATRIX.md")
    parser.add_argument(
        "--listing",
        default="artifacts/pandas_api_listing.json",
        help="Input listing JSON (default: artifacts/pandas_api_listing.json)",
    )
    parser.add_argument(
        "--out",
        default="COVERAGE_MATRIX.md",
        help="Output Markdown path (default: COVERAGE_MATRIX.md)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    listing_path = Path(args.listing)
    if not listing_path.is_absolute():
        listing_path = repo_root / listing_path
    listing = json.loads(listing_path.read_text())

    fixture_ops = load_fixture_ops(repo_root)
    breakdown, counts = classify(listing, fixture_ops)

    rendered = render(breakdown, counts, listing.get("pandas_version", "?"))
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = repo_root / out_path
    out_path.write_text(rendered)

    total_full = sum(c["full"] for c in counts.values())
    total_zero = sum(c["zero"] for c in counts.values())
    total = total_full + total_zero
    pct = (total_full / total * 100) if total else 0.0
    print(
        f"coverage_matrix: classes={len(counts)} "
        f"full={total_full} zero={total_zero} total={total} pct={pct:.1f}% → {out_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
